# Generated by Django 5.2.11 on 2026-03-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('truenas', 'TrueNAS'), ('radarr', 'Radarr'), ('sonarr', 'Sonarr'), ('overseerr', 'Overseerr'), ('jdownloader', 'JDownloader'), ('plex', 'Plex'), ('qbittorrent', 'qBittorrent'), ('tautulli', 'Tautulli'), ('prowlarr', 'Prowlarr'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField(help_text='Full base URL (e.g., http://192.168.1.100:8989)')),
                ('api_key_encrypted', models.TextField(blank=True, help_text='Stored encrypted in the database.', null=True)),
                ('username', models.CharField(blank=True, help_text='For services that require basic auth instead of an API key.', max_length=100, null=True)),
                ('password_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
