# Generated by Django 5.2.11 on 2026-03-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('truenas', 'TrueNAS'), ('radarr', 'Radarr'), ('sonarr', 'Sonarr'), ('overseerr', 'Overseerr'), ('jdownloader', 'JDownloader'), ('plex', 'Plex'), ('qbittorrent', 'qBittorrent'), ('tautulli', 'Tautulli'), ('prowlarr', 'Prowlarr'), ('bazarr', 'Bazarr'), ('other', 'Other')], max_length=50),
        ),
    ]
