# Generated by Django 6.0.3 on 2026-03-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_proxmox_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('truenas', 'TrueNAS'), ('radarr', 'Radarr'), ('sonarr', 'Sonarr'), ('overseerr', 'Overseerr'), ('jdownloader', 'JDownloader'), ('plex', 'Plex'), ('qbittorrent', 'qBittorrent'), ('tautulli', 'Tautulli'), ('prowlarr', 'Prowlarr'), ('bazarr', 'Bazarr'), ('proxmox', 'Proxmox'), ('pfsense', 'pfSense'), ('other', 'Other')], max_length=50),
        ),
    ]
